"""initial_database

Revision ID: 92af17912b7c
Revises: 
Create Date: 2026-07-04 01:20:41.096328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92af17912b7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('current_ip', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', name='clientstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_index('ix_clients_current_ip', 'clients', ['current_ip'], unique=False)
    op.create_index('ix_clients_last_seen', 'clients', ['last_seen'], unique=False)
    op.create_index('ix_clients_status', 'clients', ['status'], unique=False)
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_value', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_value')
    )
    op.create_index('ix_rates_enabled', 'rates', ['enabled'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'EXPIRED', name='sessionstatus'), nullable=False),
    sa.Column('purchased_minutes', sa.Integer(), nullable=False),
    sa.Column('remaining_minutes', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_client', 'sessions', ['client_id'], unique=False)
    op.create_index('ix_sessions_end_time', 'sessions', ['end_time'], unique=False)
    op.create_index('ix_sessions_status', 'sessions', ['status'], unique=False)
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UNUSED', 'USED', 'EXPIRED', name='voucherstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['used_by_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_vouchers_expiration', 'vouchers', ['expires_at'], unique=False)
    op.create_index('ix_vouchers_status', 'vouchers', ['status'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('COIN', 'VOUCHER', name='paymentmethod'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_created_at', 'sales', ['created_at'], unique=False)
    op.create_index('ix_sales_payment_method', 'sales', ['payment_method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_payment_method', table_name='sales')
    op.drop_index('ix_sales_created_at', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_vouchers_status', table_name='vouchers')
    op.drop_index('ix_vouchers_expiration', table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index('ix_sessions_status', table_name='sessions')
    op.drop_index('ix_sessions_end_time', table_name='sessions')
    op.drop_index('ix_sessions_client', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_rates_enabled', table_name='rates')
    op.drop_table('rates')
    op.drop_index('ix_clients_status', table_name='clients')
    op.drop_index('ix_clients_last_seen', table_name='clients')
    op.drop_index('ix_clients_current_ip', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
