table inet pisowifi {
    set authenticated_clients {
        type ipv4_addr
        flags timeout
    }

    chain input {
        type filter hook input priority filter; policy accept;
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
        ip saddr @authenticated_clients accept
        ip daddr @authenticated_clients accept
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}

table ip nat {
    set authenticated_clients {
        type ipv4_addr
        flags timeout
    }

    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        ip saddr @authenticated_clients return
        iifname "enxc817f552a5c6" udp dport 53 redirect to :53
        iifname "enxc817f552a5c6" tcp dport 53 redirect to :53
        iifname "enxc817f552a5c6" tcp dport 80 redirect to :80
    }

    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        oifname "eth0" masquerade
    }
}
