# Interface to bind to
interface=enxc817f552a5c6

# Bind dynamic interfaces as they come up
bind-dynamic

# DHCP IP Range & lease time
dhcp-range=10.0.0.20,10.0.0.254,12h

# DHCP Options (Option 3 = Gateway, Option 6 = DNS)
dhcp-option=3,10.0.0.1
dhcp-option=6,10.0.0.1

# Upstream public DNS forwarders for authenticated clients
server=1.1.1.1
server=8.8.8.8

# Authoritative local portal hostnames
address=/portal.pisowifi/10.0.0.1
address=/wifi.login/10.0.0.1
